#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me redirects to another page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "/arewrite ^/redirect_me https://www.youtube.com/watch?v=wSdT-SArM2Q permanent; /etc/nginx/sites-available/default
service nginx restart