#!/usr/bin/env bash
# Not found page 404
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "42i $ns" /etc/nginx/sites-available/default
service nginx start