#!/usr/bin/env bash
cp /etc/hosts /etc/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts.new
echo -e "\n8.8.8.8\tfacebook.com" >> /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
cat ~/hosts.new >> /etc/hosts